// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig,env } from "prisma/config";


export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});

// import {defineConfig} from 'prisma/config';
// import {PrismaPg} from '@prisma/adapter-pg';

// export default defineConfig({
//   earlyAccess: true,
//   schema: 'prisma/schema.prisma',
//   migrate:{
//     async adapter(){
//       const {Pool} = await import ('pg');
//       const pool = new Pool({
//         connectionString: process.env.DATABASE_URL,
//       })
//       return new PrismaPg(pool);
//     }
//   }

// })